### ISSUE TITLE
More Issues for Contribution

### ISSUE THREAD

**Issue by Muhimen123** [TheRenegadeCoder/how-to-python-code#4]
Wouldn't it be great to have more issues? That way, contributors(me) will know what to write about rather than roaming aimlessly.

**Comment by jrg94** [comment]
Sure! Right now, this repo is home to a series of articles I've been grinding on since late 2017. That big table in the README is a reverse chronological list of those posts with links to other goodies like challenges, videos, and source code. For now, I plan to keep that pretty much as-is.

That said, I'm open to whatever support you want to provide. If you want to write your own articles, I'd be happy to link them in a separate table/list. 

Otherwise, you're welcome to fill in anywhere there are holes in the README. For instance, I've been trying to convert all my article snippets to Jupyter notebooks. It's a slow painful process, so I haven't really prioritized it. Also, I'd love it if folks like you helped build out the social media challenges. Maybe we could get more involvement that way!

I'll make some issues, so you can see exactly what I'm looking for.

**Comment by jrg94** [comment]
Here are the two types of issues I've created:

- #5 
- #6 

Feel free to use those as templates to generate additional issues for other rows in the table. 

Also, if you're not interested in working on either of these, let me know what you'd prefer! I'm also looking for help brainstorming ideas for articles (hence [the DEV post](https://dev.to/renegadecoder94/what-python-questions-are-you-always-asking-19i7)).

**Comment by Muhimen123** [comment]
Just perfect!
